apiVersion: v1
kind: Service
metadata:
  name: test-python
  labels:
    app: test-python
  namespace: dev
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30005
  selector:
    app: test-python
